##Name: Harsh Gupta
##Roll: 44
##Section: D
##Practical: 1

Declare the list of 100000 elements and compare the performance
with the array of 100000 elements:

In [15]:
import numpy as np

In [16]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [17]:
print(my_list)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [18]:
print(my_arr)

[     0      1      2 ... 999997 999998 999999]


In [21]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]
print(my_list2)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [22]:
%time for _ in range(10): my_arr2 = [x*2 for x in my_arr]
print(my_arr2)

CPU times: user 2.52 s, sys: 174 ms, total: 2.7 s
Wall time: 2.7 s


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



1. Write a python code for addition, subtraction and multiplication of two 4x4 matrices. [Use
numpy]

In [23]:
import numpy as np

In [28]:
A = [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12],
     [13,14,15,16]]

B = [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12],
     [13,14,15,16]]

multi = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

multi = np.dot(A,B)

for r in multi:
  print(r)

[ 90 100 110 120]
[202 228 254 280]
[314 356 398 440]
[426 484 542 600]


2. Write a NumPy program to compute the following for the given array.
Mean, median, mode, variance, and standard deviation.

In [33]:
from scipy import stats

In [29]:
my_arr3 = np.arange(10)
print(my_arr3)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
mean = np.mean(my_arr3)
print(mean)

4.5


In [31]:
median = np.median(my_arr3)
print(median)

4.5


In [34]:
mode = stats.mode(my_arr3)
print(mode)

ModeResult(mode=array([0]), count=array([1]))


In [35]:
variance = np.var(my_arr3)
print(variance)

8.25


In [37]:
StdDeviation = np.std(my_arr3)
print(StdDeviation)

2.8722813232690143


3. Randomly generate the marks of the 80 students in the range of 40 to 95. Write a NumPy
program to compute the 70 percentile for all elements in a given array. (Hint: use
np.random.randint (start, stop, no_of_items) for list generation) (Hint: Use np.percentile)

In [38]:
import random

In [41]:
marks = np.random.randint(40,95,80)
print(marks)

[88 51 72 71 87 90 94 54 84 52 94 73 65 86 91 80 44 47 71 76 75 55 64 68
 91 63 71 93 44 42 65 47 89 91 85 55 86 61 91 62 52 81 41 73 45 61 85 53
 79 42 82 60 71 73 42 87 43 87 77 85 45 67 80 67 41 88 76 53 47 68 79 61
 54 52 52 81 74 70 94 92]


In [43]:
percentile = np.percentile(marks,70)
print(percentile)

81.0


4. You are given a space separated list of nine integers. Your task is to convert this list into
a 3x3 NumPy array.
Eg: input: 1 2 3 4 5 6 7 8 9
Output:
[ [1 2 3]
[4 5 6]
[7 8 9] ]
Further, compute the determinant and inverse of the array manually as well as programmatically
using python.
[HINT: to find determinant use linear algebra package under numpy. Add these statements i.e.
import numpy as np
from numpy import linalg
np.linalg.det(a) ]

In [64]:
import scipy.linalg as la

In [68]:
my_arr4=np.array([7,4,2,6,7,8,9,1,0])
my_arr4=my_arr4.reshape(3,3)
print(my_arr4)

[[7 4 2]
 [6 7 8]
 [9 1 0]]


In [69]:
det = np.linalg.det(my_arr4)
print(det)

118.00000000000004


In [70]:
inverse = la.inv(my_arr4)
print(inverse)

[[-0.06779661  0.01694915  0.15254237]
 [ 0.61016949 -0.15254237 -0.37288136]
 [-0.48305085  0.24576271  0.21186441]]


5. Create a 5 by 2 integer array from a range between 100 to 200 such that the difference
between each element is 10. Print the same.

In [45]:
my_arr5 = np.arange(100,200,10)
print(my_arr5)

[100 110 120 130 140 150 160 170 180 190]


In [51]:
my_arr5 = my_arr5.reshape(5,2)
print(my_arr5)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


6. Consider two matrices
M1=([[2,3,4], [6,5,2], [6,7,3]])
M2=([[1,4,2], [4,3,6],[5,9,8]])
Calculate manually as well as develop the python program for the following:
(1) matrix multiplication (dot product) (2) inner product (3) cross product (4) outer product


In [55]:
M1 = ([[2,3,4],
       [6,5,2],
       [6,7,3]])

M2 = ([[1,4,2],
       [4,3,6],
       [5,9,8]])

result = ([[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]])

result = np.dot(M1,M2)

for r in result:
  print(r)

[34 53 54]
[36 57 58]
[49 72 78]


In [56]:
inner = np.inner(M1,M2)
print(inner)

[[ 22  41  69]
 [ 30  51  91]
 [ 40  63 117]]


In [57]:
cross = np.cross(M1,M2)
print(cross)

[[-10   0   5]
 [ 24 -28  -2]
 [ 29 -33  19]]


In [58]:
outer = np.outer(M1,M2)
print(outer)

[[ 2  8  4  8  6 12 10 18 16]
 [ 3 12  6 12  9 18 15 27 24]
 [ 4 16  8 16 12 24 20 36 32]
 [ 6 24 12 24 18 36 30 54 48]
 [ 5 20 10 20 15 30 25 45 40]
 [ 2  8  4  8  6 12 10 18 16]
 [ 6 24 12 24 18 36 30 54 48]
 [ 7 28 14 28 21 42 35 63 56]
 [ 3 12  6 12  9 18 15 27 24]]


7. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.
Arr =([[1,4,8], [8,9,2],[9,7,8]])
HINT:
Use linear algebra package under numpy. Add these statements i.e. for
eigenvalues

In [71]:
my_arr7=([[1,4,8],
          [8,9,2],
          [9,7,8]])

result = np.linalg.eig(my_arr7)
print(result)

(array([18.61713304, -4.50451282,  3.88737977]), array([[-0.44798294, -0.82768979,  0.36471887],
       [-0.52339057,  0.43844259, -0.77347804],
       [-0.7248266 ,  0.35028233,  0.51837426]]))


In [ ]:
8. Write a NumPy program to compute the covariance matrix of two given arrays

In [72]:
Mat1 = ([[2,3,4],
       [6,5,2],
       [6,7,3]])

Mat2 = ([[1,4,2],
       [4,3,6],
       [5,9,8]])

CovMatrix = np.cov(Mat1,Mat2)
print(CovMatrix)

[[ 1.         -2.         -1.5         0.5         1.          1.5       ]
 [-2.          4.33333333  3.83333333 -0.16666667 -2.66666667 -2.16666667]
 [-1.5         3.83333333  4.33333333  1.33333333 -3.16666667 -0.16666667]
 [ 0.5        -0.16666667  1.33333333  2.33333333 -1.16666667  2.83333333]
 [ 1.         -2.66666667 -3.16666667 -1.16666667  2.33333333 -0.16666667]
 [ 1.5        -2.16666667 -0.16666667  2.83333333 -0.16666667  4.33333333]]


9. Write a Python program to count number of occurrences of each value in a given array of non-negative integers. USE bincount

In [78]:
my_arr9 = ([1,4,8,2,3,6,7,2,9,5,4])

Occurence = np.bincount(my_arr9)
print(Occurence)

[0 1 2 1 2 1 1 1 1 1]


10. Write a NumPy program to compute the sum of the diagonal element of a given array. USE trace

In [77]:
my_arr10 = ([[2,3,4],
            [6,5,2],
            [6,7,3]])

trace = np.trace(my_arr10)
print(trace)

10
